//! Pure stub-content generators. Each returns content for one referenced file;
//! file-system orchestration (paths, skip-if-exists, manifest) lives in the
//! parent dispatcher.

use super::typemap::params_from_input_schema;
use serde_json::{Value, json};

/// Title-case a filename stem for placeholder document titles.
/// "sales_data.pdf" -> "Sales Data".
fn title_from_filename(filename: &str) -> String {
    let stem = std::path::Path::new(filename).file_stem().and_then(|s| s.to_str()).unwrap_or(filename);
    stem.split(['_', '-', ' '])
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Typed python tool stub from `input_schema`. Signature uses named, typed
/// kwargs (never `def main(params)`), matching the implementation template's
/// contract. `func_name` is the entry-point function (from `module:func`).
pub fn python_tool_stub(func_name: &str, input_schema: &Value) -> String {
    let params = params_from_input_schema(input_schema);
    let sig_params = if params.is_empty() { String::new() } else { params.iter().map(|(name, ty)| format!("{name}: {ty}")).collect::<Vec<_>>().join(", ") };
    let body = if params.is_empty() {
        "    # TODO: implement\n    return {}\n".to_string()
    } else {
        let echoed = params.iter().map(|(name, _)| format!("\"{name}\": {name}")).collect::<Vec<_>>().join(", ");
        format!("    # TODO: implement\n    return {{{echoed}}}\n")
    };
    format!("def {func_name}({sig_params}) -> dict:\n    \"\"\"TODO: describe what this tool does.\"\"\"\n{body}")
}

/// `schema.yaml` content for a python tool: exactly `input_schema` +
/// `output_schema`, both objects (matches `ToolSchemas` consumed by
/// `load_schemas`). Defaults a bare object when a schema is absent.
pub fn tool_schema_yaml(input_schema: &Value, output_schema: Option<&Value>) -> anyhow::Result<String> {
    let empty = json!({"type": "object"});
    let mut map = serde_json::Map::new();
    map.insert("input_schema".to_string(), if input_schema.is_object() { input_schema.clone() } else { empty.clone() });
    map.insert("output_schema".to_string(), output_schema.cloned().unwrap_or(empty));
    Ok(serde_norway::to_string(&map)?)
}

/// Default requirements.txt content for a scaffolded python tool.
pub fn tool_requirements() -> &'static str {
    "# Auto-generated by wxctl compose scaffold\n"
}

/// Placeholder knowledge-base document. `filename` decides the title and the
/// returned content matches `.md` (heading + prose) vs anything else (plain text).
pub fn kb_document_stub(filename: &str) -> String {
    let title = title_from_filename(filename);
    let is_md = std::path::Path::new(filename).extension().and_then(|e| e.to_str()).map(|e| e.eq_ignore_ascii_case("md")).unwrap_or(false);
    let prose = format!("This is a placeholder document for {title}. Replace this text with the real source content before deploying. The knowledge base indexes this file so an agent can retrieve and cite it.");
    if is_md { format!("# {title}\n\n{prose}\n") } else { format!("{title}\n\n{prose}\n") }
}

/// Runnable WML score-stub. Matches the WML function contract: a top-level
/// `score(payload)` returning a fixed `predictions` payload. `hash_and_tag_source`
/// only reads the bytes, so this need not execute, but it is valid runnable Python.
pub fn wml_score_stub() -> &'static str {
    "def score(payload):\n    \"\"\"WML scoring entry point — returns a fixed prediction payload.\"\"\"\n    input_data = payload.get(\"input_data\", [{}])\n    values = input_data[0].get(\"values\", []) if input_data else []\n    return {\"predictions\": [{\"values\": values}]}\n"
}

/// Minimal valid OAS3 document (one GET operation). The OpenAPI artifact
/// builder only zips/reads the file at validate time, so this need only be a
/// parseable OAS3 doc. Returns YAML.
pub fn openapi_spec_stub() -> &'static str {
    "openapi: 3.0.3\ninfo:\n  title: Scaffolded API\n  version: 1.0.0\n  description: Placeholder OpenAPI spec generated by wxctl compose scaffold.\npaths:\n  /ping:\n    get:\n      operationId: ping\n      summary: Health check\n      responses:\n        '200':\n          description: OK\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  status:\n                    type: string\n"
}

/// Minimal flow document. `load_flow_model` requires `spec.name` +
/// `spec.description`; a single noop node keeps it structurally complete.
/// `flow_name` is derived from the referenced filename stem.
pub fn flow_doc_stub(flow_name: &str) -> String {
    json!({
        "spec": {
            "name": flow_name,
            "description": format!("Placeholder flow '{flow_name}' generated by wxctl compose scaffold. Replace with the real flow definition."),
        },
        "nodes": {},
        "edges": [],
    })
    .to_string()
        + "\n"
}

/// Serialize the flow doc as YAML (the loader accepts .json/.yaml/.yml; the
/// dispatcher picks the serializer by the referenced extension).
pub fn flow_doc_stub_yaml(flow_name: &str) -> anyhow::Result<String> {
    let v: Value = json!({
        "spec": {
            "name": flow_name,
            "description": format!("Placeholder flow '{flow_name}' generated by wxctl compose scaffold. Replace with the real flow definition."),
        },
        "nodes": {},
        "edges": [],
    });
    Ok(serde_norway::to_string(&v)?)
}

/// Minimal FastMCP python server with one echo tool. Not validate-gated
/// (toolkit has no post_validate), generated for full coverage.
pub fn fastmcp_server_stub() -> &'static str {
    "from fastmcp import FastMCP\n\nmcp = FastMCP(\"scaffolded-server\")\n\n\n@mcp.tool()\ndef echo(text: str) -> str:\n    \"\"\"Echo the input text back to the caller.\"\"\"\n    return text\n\n\nif __name__ == \"__main__\":\n    mcp.run()\n"
}

/// requirements.txt for the FastMCP toolkit server.
pub fn fastmcp_requirements() -> &'static str {
    "fastmcp\n"
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn python_stub_is_typed_with_and_without_params() {
        // With properties → typed positional params + typed return; never a generic params/**kwargs sig.
        let schema = json!({
            "type": "object",
            "properties": { "city": { "type": "string" }, "days": { "type": "integer" } },
            "required": ["city", "days"]
        });
        let stub = python_tool_stub("main", &schema);
        assert!(stub.contains("def main(city: str, days: int) -> dict:"), "got: {stub}");
        assert!(!stub.contains("def main(params)"));
        assert!(!stub.contains("**kwargs"));

        // No properties → no params, still a typed return.
        let stub = python_tool_stub("run", &json!({"type": "object"}));
        assert!(stub.contains("def run() -> dict:"), "got: {stub}");
    }

    #[test]
    fn tool_schema_yaml_has_both_objects() {
        let y = tool_schema_yaml(&json!({"type": "object", "properties": {}}), None).unwrap();
        assert!(y.contains("input_schema"));
        assert!(y.contains("output_schema"));
        // Round-trips back into the ToolSchemas shape (objects).
        let v: serde_json::Value = serde_norway::from_str(&y).unwrap();
        assert!(v.get("input_schema").unwrap().is_object());
        assert!(v.get("output_schema").unwrap().is_object());
    }

    #[test]
    fn kb_md_vs_txt() {
        let md = kb_document_stub("sales_data.md");
        assert!(md.starts_with("# Sales Data"));
        let txt = kb_document_stub("policy.txt");
        assert!(txt.starts_with("Policy\n"));
        assert!(!txt.starts_with("#"));
    }

    #[test]
    fn wml_score_has_predictions() {
        assert!(wml_score_stub().contains("def score(payload):"));
        assert!(wml_score_stub().contains("\"predictions\""));
    }

    #[test]
    fn openapi_stub_parses_as_oas3() {
        let v: serde_json::Value = serde_norway::from_str(openapi_spec_stub()).unwrap();
        assert_eq!(v.get("openapi").and_then(|x| x.as_str()), Some("3.0.3"));
        assert!(v.pointer("/paths/~1ping/get/operationId").is_some());
    }

    #[test]
    fn flow_stub_has_spec_name_and_description() {
        let s = flow_doc_stub("my_flow");
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert_eq!(v.pointer("/spec/name").and_then(|x| x.as_str()), Some("my_flow"));
        assert!(v.pointer("/spec/description").and_then(|x| x.as_str()).is_some());
        let y = flow_doc_stub_yaml("my_flow").unwrap();
        let vy: serde_json::Value = serde_norway::from_str(&y).unwrap();
        assert_eq!(vy.pointer("/spec/name").and_then(|x| x.as_str()), Some("my_flow"));
    }

    #[test]
    fn fastmcp_stub_has_echo_tool() {
        assert!(fastmcp_server_stub().contains("def echo(text: str) -> str:"));
        assert!(fastmcp_server_stub().contains("FastMCP"));
    }
}
