//! Static IR codegen emitter.
//!
//! Turns the owned schema model (`crate::definition::*`) into Rust source text
//! for the `crate::ir::*` type family declared in `wxctl-schema/src/ir.rs`.
//! `generate_ir` is called once by `wxctl-schema/build.rs`; its output is
//! written to `OUT_DIR/schema_ir_generated.rs` and `include!`d from
//! `wxctl-schema/src/ir.rs`, so every `crate::ir::…` path below resolves inside
//! that crate's `ir` module once spliced in.
//!
//! All emitted values are const-constructible (`&'static str`, `&'static [..]`,
//! nested `&IrStruct { .. }` literals) — Rust's rvalue static promotion turns
//! each nested reference into a `'static` without an intermediate named static,
//! so one kind is one promoted top-level `static` literal.

use crate::build_meta::ParsedSchema;
use crate::definition::*;
use crate::deployment::Deployment;
use semver::Version;
use std::collections::HashMap;
use std::fmt::Write as _;

// ---------------------------------------------------------------------------
// Step 1: public entry point
// ---------------------------------------------------------------------------

/// Emit the static-IR Rust source for every schema in `schemas`, iterated over
/// `order` (topo order, index-aligned with `codegen::tables`).
pub fn generate_ir(order: &[String], schemas: &[ParsedSchema]) -> String {
    let by_name: HashMap<&str, &ParsedSchema> = schemas.iter().map(|p| (p.schema.resource.name.as_str(), p)).collect();

    let mut code = String::new();
    writeln!(code, "// Auto-generated by build.rs (via wxctl-schema-compiler::codegen::ir) - DO NOT EDIT").unwrap();
    writeln!(code).unwrap();

    // (kind, deployment-key, effective-static-path) for RESOURCE_IR_EFFECTIVE,
    // accumulated in the same topo order the per-kind statics are emitted.
    let mut effective_entries: Vec<(String, String, String)> = Vec::new();
    // (kind, static-path) pairs for the two phf lookups, built alongside the
    // per-kind statics so both passes iterate `order` identically.
    let mut resource_ir_entries: Vec<(String, String)> = Vec::new();
    let mut descriptor_ir_entries: Vec<(String, String)> = Vec::new();

    for name in order {
        let Some(parsed) = by_name.get(name.as_str()) else {
            continue;
        };
        let def = &parsed.schema.resource;
        let upper = ident_upper(&def.kind);
        let schema_static = format!("SCHEMA_IR_{upper}");
        let descriptor_static = format!("DESCRIPTOR_IR_{upper}");

        // 1. Base SchemaIr.
        writeln!(code, "pub static {schema_static}: crate::ir::SchemaIr = {};", emit_schema_ir(&parsed.schema)).unwrap();

        // 2. Per-deployment effective SchemaIr, one per declared overlay key
        // (only when the deployments map is non-empty — `deployments: {}` emits
        // no variant, the base applies everywhere).
        if let Some(deployments) = &def.deployments
            && !deployments.is_empty()
        {
            let mut keys: Vec<&String> = deployments.keys().collect();
            keys.sort();
            for key in keys {
                let deployment = deployment_for_key(key);
                let effective = crate::overlay::effective_definition(def, &deployment).unwrap_or_else(|e| panic!("effective_definition failed for kind '{}' deployment key '{key}': {e}", def.kind));
                let variant_static = format!("{schema_static}__{}", sanitize_key_ident(key));
                let effective_schema = ResourceSchema { resource: effective };
                writeln!(code, "pub static {variant_static}: crate::ir::SchemaIr = {};", emit_schema_ir(&effective_schema)).unwrap();
                effective_entries.push((def.kind.clone(), key.clone(), variant_static));
            }
        }

        // 3. DescriptorIr — endpoint-fallback logic from descriptor.rs:34-61.
        // `schema` references the base static declared just above rather than
        // re-emitting the (potentially large) SchemaIr literal a second time.
        writeln!(code, "pub static {descriptor_static}: crate::ir::DescriptorIr = {};", emit_descriptor_ir(def, &schema_static)).unwrap();
        writeln!(code).unwrap();

        resource_ir_entries.push((def.kind.clone(), format!("&{schema_static}")));
        descriptor_ir_entries.push((def.kind.clone(), format!("&{descriptor_static}")));
    }

    // 4. Lookups.
    let mut resource_ir_map = phf_codegen::Map::new();
    let resource_ir_entries: Vec<(&str, String)> = resource_ir_entries.iter().map(|(k, v)| (k.as_str(), v.clone())).collect();
    for (kind, path) in &resource_ir_entries {
        resource_ir_map.entry(*kind, path);
    }
    writeln!(code, "pub static RESOURCE_IR: phf::Map<&'static str, &'static crate::ir::SchemaIr> = {};", resource_ir_map.build()).unwrap();
    writeln!(code).unwrap();

    let mut descriptor_ir_map = phf_codegen::Map::new();
    let descriptor_ir_entries: Vec<(&str, String)> = descriptor_ir_entries.iter().map(|(k, v)| (k.as_str(), v.clone())).collect();
    for (kind, path) in &descriptor_ir_entries {
        descriptor_ir_map.entry(*kind, path);
    }
    writeln!(code, "pub static RESOURCE_DESCRIPTOR_IR: phf::Map<&'static str, &'static crate::ir::DescriptorIr> = {};", descriptor_ir_map.build()).unwrap();
    writeln!(code).unwrap();

    // NOTE: no inline `'static` on the tuple's reference fields (unlike the
    // `RESOURCE_IR`/`RESOURCE_DESCRIPTOR_IR` phf::Map statics above) — clippy's
    // `redundant_static_lifetimes` recurses into a slice-of-tuple static's type
    // (though not into opaque generic type params like `phf::Map<K, V>`), and
    // flags an explicit `'static` here as redundant since it's already implied.
    writeln!(code, "/// (kind, deployment-key, effective IR) for every non-empty `deployments` overlay.").unwrap();
    writeln!(code, "pub static RESOURCE_IR_EFFECTIVE: &[(&str, &str, &crate::ir::SchemaIr)] = &[").unwrap();
    for (kind, key, static_path) in &effective_entries {
        writeln!(code, "    ({}, {}, &{static_path}),", esc(kind), esc(key)).unwrap();
    }
    writeln!(code, "];").unwrap();

    code
}

// ---------------------------------------------------------------------------
// Deployment-key handling
// ---------------------------------------------------------------------------

/// Sanitize a `deployments:` overlay key into a valid Rust identifier fragment
/// (e.g. `software-5.3` -> `SOFTWARE_5_3`).
fn sanitize_key_ident(key: &str) -> String {
    key.to_uppercase().replace(['-', '.'], "_")
}

/// Mangle a resource `kind` into the uppercase fragment used in generated
/// static names (e.g. `database_connection` -> `DATABASE_CONNECTION`), mirroring
/// `build.rs`'s `mangle_name` convention.
fn ident_upper(kind: &str) -> String {
    kind.to_uppercase().replace('-', "_")
}

/// Construct a concrete `Deployment` that selects exactly the given overlay key
/// when run through `overlay::effective_definition`'s `select_overlay_key`.
/// Every overlay key in the current schema set is a bare `"saas"`/`"software"`
/// or a `"software-<version-prefix>"` form (e.g. `"software-5.3"`); this padds
/// the leading numeric components of the suffix to a full major.minor.patch
/// triple. Arbitrary range/operator constraints (`"software->=5.3, <6"`) are
/// not synthesized here — none occur in the schema set today.
fn deployment_for_key(key: &str) -> Deployment {
    if key == "saas" {
        return Deployment::Saas;
    }
    if key == "software" {
        return Deployment::Software { version: Version::new(0, 0, 0) };
    }
    let rest = key.strip_prefix("software-").unwrap_or_else(|| panic!("unrecognized deployment overlay key {key:?}: expected \"saas\", \"software\", or \"software-<version>\""));
    if let Ok(v) = Version::parse(rest) {
        return Deployment::Software { version: v };
    }
    let parts: Vec<u64> = rest.split('.').map(|p| p.trim_end_matches(['x', 'X', '*']).parse::<u64>().unwrap_or_else(|_| panic!("cannot derive a representative version for deployment overlay key {key:?}: non-numeric component {p:?}"))).collect();
    let major = parts.first().copied().unwrap_or(0);
    let minor = parts.get(1).copied().unwrap_or(0);
    let patch = parts.get(2).copied().unwrap_or(0);
    Deployment::Software { version: Version::new(major, minor, patch) }
}

// ---------------------------------------------------------------------------
// Step 2: literal-emission helpers (D2 untyped-JSON, D3 sorted maps)
// ---------------------------------------------------------------------------

// Untyped fields → canonical JSON string literal (D2). serde_json::Value serializes canonically;
// escape it into a Rust string literal with {:?}.
fn json_lit(v: &serde_json::Value) -> String {
    format!("{:?}", serde_json::to_string(v).expect("canonical json"))
}
// serde_norway::Value (prompt / overlay bodies) → serde_json::Value first, then json_lit.
fn yaml_to_json_lit(v: &serde_norway::Value) -> String {
    let j: serde_json::Value = serde_json::to_value(v).expect("yaml→json"); // structural, lossless for these shapes
    json_lit(&j)
}

/// Escape a plain string into a Rust string literal.
fn esc(s: &str) -> String {
    format!("{s:?}")
}

/// `Option<T>` → `Some(<f(x)>)` / `None`.
fn opt<T>(v: &Option<T>, f: impl Fn(&T) -> String) -> String {
    match v {
        Some(x) => format!("Some({})", f(x)),
        None => "None".to_string(),
    }
}

/// `&[T]` → `&[f(item), ...]`.
fn slice<T>(items: &[T], f: impl Fn(&T) -> String) -> String {
    let body: String = items.iter().map(|i| format!("{}, ", f(i))).collect();
    format!("&[{body}]")
}

/// `HashMap<String, V>` (D3) → `&[(key, f(val)), ...]` sorted by key.
fn sorted_pairs<V>(map: &HashMap<String, V>, f: impl Fn(&V) -> String) -> String {
    let mut keys: Vec<&String> = map.keys().collect();
    keys.sort();
    let body: String = keys.iter().map(|k| format!("({}, {}), ", esc(k), f(&map[k.as_str()]))).collect();
    format!("&[{body}]")
}

/// A `DeploymentOverlay` sub-block: `"null"` when absent (mirrors
/// `Value::is_null` skip_serializing_if), else its canonical JSON literal.
fn yaml_value_or_null_lit(v: &serde_norway::Value) -> String {
    if v.is_null() { esc("null") } else { yaml_to_json_lit(v) }
}

// ---------------------------------------------------------------------------
// Enum → `crate::ir::…Ir` variant path.
// ---------------------------------------------------------------------------

fn field_type_ir(t: &FieldType) -> &'static str {
    match t {
        FieldType::String => "crate::ir::FieldTypeIr::String",
        FieldType::Integer => "crate::ir::FieldTypeIr::Integer",
        FieldType::Float => "crate::ir::FieldTypeIr::Float",
        FieldType::Boolean => "crate::ir::FieldTypeIr::Boolean",
        FieldType::Object => "crate::ir::FieldTypeIr::Object",
        FieldType::Array => "crate::ir::FieldTypeIr::Array",
        FieldType::Timestamp => "crate::ir::FieldTypeIr::Timestamp",
    }
}

fn field_location_ir(l: &FieldLocation) -> &'static str {
    match l {
        FieldLocation::Body => "crate::ir::FieldLocationIr::Body",
        FieldLocation::Query => "crate::ir::FieldLocationIr::Query",
        FieldLocation::Header => "crate::ir::FieldLocationIr::Header",
        FieldLocation::Path => "crate::ir::FieldLocationIr::Path",
        FieldLocation::Computed => "crate::ir::FieldLocationIr::Computed",
        FieldLocation::LocalOnly => "crate::ir::FieldLocationIr::LocalOnly",
    }
}

fn http_method_ir(m: &HttpMethod) -> &'static str {
    match m {
        HttpMethod::Get => "crate::ir::HttpMethodIr::Get",
        HttpMethod::Post => "crate::ir::HttpMethodIr::Post",
        HttpMethod::Put => "crate::ir::HttpMethodIr::Put",
        HttpMethod::Patch => "crate::ir::HttpMethodIr::Patch",
        HttpMethod::Delete => "crate::ir::HttpMethodIr::Delete",
    }
}

fn discovery_method_ir(m: &DiscoveryMethod) -> &'static str {
    match m {
        DiscoveryMethod::ListAndGet => "crate::ir::DiscoveryMethodIr::ListAndGet",
        DiscoveryMethod::GetById => "crate::ir::DiscoveryMethodIr::GetById",
        DiscoveryMethod::Skip => "crate::ir::DiscoveryMethodIr::Skip",
        DiscoveryMethod::Singleton => "crate::ir::DiscoveryMethodIr::Singleton",
    }
}

fn update_strategy_ir(u: &UpdateStrategy) -> &'static str {
    match u {
        UpdateStrategy::Patch => "crate::ir::UpdateStrategyIr::Patch",
        UpdateStrategy::Replace => "crate::ir::UpdateStrategyIr::Replace",
        UpdateStrategy::Recreate => "crate::ir::UpdateStrategyIr::Recreate",
    }
}

fn hash_storage_ir(h: &HashStorage) -> &'static str {
    match h {
        HashStorage::NameSuffix => "crate::ir::HashStorageIr::NameSuffix",
        HashStorage::Tag => "crate::ir::HashStorageIr::Tag",
        HashStorage::EnvMarker => "crate::ir::HashStorageIr::EnvMarker",
        HashStorage::ServerSide => "crate::ir::HashStorageIr::ServerSide",
        HashStorage::Local => "crate::ir::HashStorageIr::Local",
    }
}

// ---------------------------------------------------------------------------
// Recursive owned → `crate::ir::SchemaIr { .. }` literal emitter.
// ---------------------------------------------------------------------------

fn emit_schema_ir(schema: &ResourceSchema) -> String {
    format!("crate::ir::SchemaIr {{ resource: {} }}", emit_resource_def_ir(&schema.resource))
}

fn emit_resource_def_ir(def: &ResourceDefinition) -> String {
    let deployments = opt(&def.deployments, |m| sorted_pairs(m, emit_overlay_ir));
    let unsupported_on = slice(&def.unsupported_on, |c| esc(&c.to_string()));
    let description = opt(&def.description, |s| esc(s));
    let prompt = opt(&def.prompt, yaml_to_json_lit);
    format!(
        "crate::ir::ResourceDefIr {{ name: {}, service: {}, kind: {}, version: {}, api: {}, schema: {}, reconciliation: {}, hooks: {}, deployments: {deployments}, unsupported_on: {unsupported_on}, description: {description}, prompt: {prompt} }}",
        esc(&def.name),
        esc(&def.service),
        esc(&def.kind),
        esc(&def.version),
        emit_api_ir(&def.api),
        emit_schema_body_ir(&def.schema),
        emit_recon_ir(&def.reconciliation),
        emit_hook_ir(&def.hooks),
    )
}

fn emit_overlay_ir(o: &DeploymentOverlay) -> String {
    format!("crate::ir::OverlayIr {{ api: {}, schema: {}, reconciliation: {}, hooks: {} }}", yaml_value_or_null_lit(&o.api), yaml_value_or_null_lit(&o.schema), yaml_value_or_null_lit(&o.reconciliation), yaml_value_or_null_lit(&o.hooks),)
}

fn emit_api_ir(api: &ApiDefinition) -> String {
    format!(
        "crate::ir::ApiIr {{ base_path: {}, id_field: {}, list_endpoint: {}, get_endpoint: {}, create_endpoint: {}, create_method: {}, update_endpoint: {}, update_method: {}, delete_endpoint: {}, delete_method: {}, readiness: {} }}",
        esc(&api.base_path),
        esc(&api.id_field),
        opt(&api.list_endpoint, |s| esc(s)),
        esc(&api.get_endpoint),
        opt(&api.create_endpoint, |s| esc(s)),
        http_method_ir(&api.create_method),
        opt(&api.update_endpoint, |s| esc(s)),
        opt(&api.update_method, |m| http_method_ir(m).to_string()),
        opt(&api.delete_endpoint, |s| esc(s)),
        http_method_ir(&api.delete_method),
        opt(&api.readiness, emit_readiness_ir),
    )
}

fn emit_readiness_ir(r: &ReadinessDefinition) -> String {
    format!("crate::ir::ReadinessIr {{ state_path: {}, ready: {}, failed: {}, timeout_env: {}, timeout_default: {}, interval_secs: {} }}", esc(&r.state_path), slice(&r.ready, |s| esc(s)), slice(&r.failed, |s| esc(s)), opt(&r.timeout_env, |s| esc(s)), r.timeout_default, r.interval_secs,)
}

fn emit_schema_body_ir(s: &SchemaDefinition) -> String {
    let fields = slice(&s.fields, emit_field_ir);
    let discriminator = opt(&s.discriminator, |s| esc(s));
    let variants = opt(&s.variants, |m| sorted_pairs(m, emit_variant_ir));
    format!("crate::ir::SchemaBodyIr {{ fields: {fields}, discriminator: {discriminator}, variants: {variants} }}")
}

fn emit_variant_ir(v: &VariantDefinition) -> String {
    format!("crate::ir::VariantIr {{ applies_to: {}, fields: {} }}", slice(&v.applies_to, |s| esc(s)), slice(&v.fields, emit_field_ir))
}

fn emit_field_ir(f: &FieldDefinition) -> String {
    format!(
        "crate::ir::FieldIr {{ name: {}, field_type: {}, required: {}, immutable: {}, location: {}, description: {}, validation: {}, schema: {}, item_type: {}, default: {}, allowed_values: {}, references: {}, api_field: {}, sensitive: {}, also_query: {}, is_path: {}, synthesize: {}, synth_shape: {} }}",
        esc(&f.name),
        field_type_ir(&f.field_type),
        f.required,
        f.immutable,
        field_location_ir(&f.location),
        opt(&f.description, |s| esc(s)),
        opt(&f.validation, emit_validation_ir),
        opt(&f.schema, |s| format!("&{}", emit_schema_body_ir(s))),
        opt(&f.item_type, |t| field_type_ir(t).to_string()),
        opt(&f.default, json_lit),
        opt(&f.allowed_values, |v| slice(v, |s| esc(s))),
        opt(&f.references, emit_field_references_ir),
        opt(&f.api_field, |s| esc(s)),
        f.sensitive,
        f.also_query,
        f.is_path,
        opt(&f.synthesize, |b| b.to_string()),
        opt(&f.synth_shape, |s| esc(s)),
    )
}

fn emit_validation_ir(v: &ValidationRules) -> String {
    format!(
        "crate::ir::ValidationIr {{ min_length: {}, max_length: {}, max_length_bytes: {}, pattern: {}, min_value: {}, max_value: {}, max_items: {}, soft_allowed_values: {}, one_of: {}, extra_rules: {} }}",
        opt(&v.min_length, |n| n.to_string()),
        opt(&v.max_length, |n| n.to_string()),
        opt(&v.max_length_bytes, |n| n.to_string()),
        opt(&v.pattern, |s| esc(s)),
        opt(&v.min_value, |n| n.to_string()),
        opt(&v.max_value, |n| n.to_string()),
        opt(&v.max_items, |n| n.to_string()),
        opt(&v.soft_allowed_values, |vv| slice(vv, |s| esc(s))),
        opt(&v.one_of, |vv| slice(vv, |inner| slice(inner, |s| esc(s)))),
        opt(&v.extra_rules, |vv| slice(vv, |s| esc(s))),
    )
}

fn emit_field_references_ir(r: &FieldReferences) -> String {
    format!("crate::ir::FieldReferencesIr {{ resource: {}, field: {}, also_allows: {}, optional: {}, require_ready: {}, relationship: {} }}", esc(&r.resource), esc(&r.field), slice(&r.also_allows, |s| esc(s)), r.optional, r.require_ready, opt(&r.relationship, |s| esc(s)),)
}

fn emit_recon_ir(r: &ReconciliationDefinition) -> String {
    format!(
        "crate::ir::ReconIr {{ discovery: {}, identity_hash: {}, state_fields: {}, update_strategy: {}, immutable_fields: {}, reject_on_immutable_drift: {}, use_json_patch: {}, json_patch_path_prefix: {} }}",
        emit_discovery_ir(&r.discovery),
        opt(&r.identity_hash, emit_identity_hash_ir),
        opt(&r.state_fields, |v| slice(v, |s| esc(s))),
        update_strategy_ir(&r.update_strategy),
        slice(&r.immutable_fields, |s| esc(s)),
        r.reject_on_immutable_drift,
        r.use_json_patch,
        opt(&r.json_patch_path_prefix, |s| esc(s)),
    )
}

fn emit_identity_hash_ir(h: &IdentityHash) -> String {
    format!("crate::ir::IdentityHashIr {{ fields: {}, nonce_field: {}, storage: {}, length: {} }}", slice(&h.fields, |s| esc(s)), opt(&h.nonce_field, |s| esc(s)), hash_storage_ir(&h.storage), h.length,)
}

fn emit_discovery_ir(d: &DiscoveryDefinition) -> String {
    format!(
        "crate::ir::DiscoveryIr {{ method: {}, list_field: {}, id_source: {}, name_field: {}, identity_match: {}, absent_when: {}, list_method: {}, list_body: {}, list_map: {}, list_filter: {} }}",
        discovery_method_ir(&d.method),
        opt(&d.list_field, |s| esc(s)),
        esc(&d.id_source),
        opt(&d.name_field, |s| esc(s)),
        opt(&d.identity_match, emit_identity_match_ir),
        opt(&d.absent_when, emit_absent_when_ir),
        opt(&d.list_method, |s| esc(s)),
        opt(&d.list_body, json_lit),
        d.list_map,
        opt(&d.list_filter, emit_list_filter_ir),
    )
}

fn emit_absent_when_ir(a: &AbsentWhen) -> String {
    format!("crate::ir::AbsentWhenIr {{ field: {}, equals: {} }}", esc(&a.field), json_lit(&a.equals))
}

fn emit_identity_match_ir(m: &IdentityMatch) -> String {
    format!("crate::ir::IdentityMatchIr {{ local_path: {}, remote_path: {} }}", esc(&m.local_path), esc(&m.remote_path))
}

fn emit_list_filter_ir(f: &ListFilter) -> String {
    format!("crate::ir::ListFilterIr {{ field: {}, equals: {} }}", esc(&f.field), esc(&f.equals))
}

fn emit_hook_ir(h: &HookDefinition) -> String {
    format!(
        "crate::ir::HookIr {{ pre_create: {}, post_create: {}, pre_update: {}, post_update: {}, pre_delete: {}, post_delete: {} }}",
        opt(&h.pre_create, |s| esc(s)),
        opt(&h.post_create, |s| esc(s)),
        opt(&h.pre_update, |s| esc(s)),
        opt(&h.post_update, |s| esc(s)),
        opt(&h.pre_delete, |s| esc(s)),
        opt(&h.post_delete, |s| esc(s)),
    )
}

// ---------------------------------------------------------------------------
// Descriptor IR — endpoint-fallback logic mirrors descriptor.rs:34-61.
// ---------------------------------------------------------------------------

/// `schema_static` is the already-emitted `SCHEMA_IR_<UPPER>` static's name —
/// the descriptor's `schema` field references it rather than re-emitting a
/// second copy of the (potentially large) `SchemaIr` literal.
fn emit_descriptor_ir(def: &ResourceDefinition, schema_static: &str) -> String {
    let create = def.api.create_endpoint.clone().unwrap_or_else(|| def.api.base_path.clone());
    let update = def.api.update_method.as_ref().map(|_| def.api.update_endpoint.clone().unwrap_or_else(|| def.api.get_endpoint.clone()));
    let delete = def.api.delete_endpoint.clone().unwrap_or_else(|| def.api.get_endpoint.clone());

    let endpoints = format!(
        "crate::ir::EndpointsIr {{ base_path: {}, list: {}, get: {}, create: {}, update: {}, update_method: {}, delete: {} }}",
        esc(&def.api.base_path),
        opt(&def.api.list_endpoint, |s| esc(s)),
        esc(&def.api.get_endpoint),
        esc(&create),
        opt(&update, |s| esc(s)),
        opt(&def.api.update_method, |m| http_method_ir(m).to_string()),
        esc(&delete),
    );

    let fields = slice(&def.schema.fields, |f: &FieldDefinition| format!("crate::ir::FieldDescriptorIr {{ name: {}, required: {}, immutable: {}, location: {} }}", esc(&f.name), f.required, f.immutable, field_location_ir(&f.location)));

    format!("crate::ir::DescriptorIr {{ name: {}, service: {}, kind: {}, id_field: {}, endpoints: {endpoints}, fields: {fields}, schema: &{schema_static} }}", esc(&def.name), esc(&def.service), esc(&def.kind), esc(&def.api.id_field),)
}
