use anyhow::{Result, anyhow};
use serde_json::{Value, json};
use std::future::Future;
use std::pin::Pin;
use wxctl_core::client::HttpClient;
use wxctl_core::registry::FieldDescriptor;
use wxctl_core::traits::{HookOutcome, ResourceHandler};

const PLATFORM_URL: &str = "https://api.dataplatform.cloud.ibm.com";

pub struct WmlDeploymentHandler;

/// Ensure task credentials exist for the space. WML deployments require
/// task credentials (an API key stored via the platform API) to run.
/// If none exist, create them using the current auth token's API key.
async fn ensure_task_credentials(client: &HttpClient, space_id: &str, operation_id: &str) -> Result<()> {
    let token = client.get_token().await?;
    let raw = client.raw_client();

    // Check if task credentials already exist for this space
    let list_url = format!("{PLATFORM_URL}/v1/task_credentials?space_id={space_id}");
    let response = raw.get(&list_url).header("Authorization", format!("Bearer {token}")).send().await.map_err(|e| anyhow!("[{operation_id}] Failed to list task credentials: {e}"))?;

    if response.status().is_success() {
        let body: Value = response.json().await.unwrap_or_default();
        let creds = body.get("credentials").and_then(|v| v.as_array());
        if let Some(creds) = creds
            && !creds.is_empty()
        {
            // Delete existing credentials and recreate with current API key
            // to avoid stale key issues
            for cred in creds {
                if let Some(cred_id) = cred.get("id").and_then(|v| v.as_str()) {
                    tracing::debug!(
                        target: "wxctl::substage::provider",
                        operation_id = %operation_id,
                        resource_type = "wml_deployment",
                        space_id = %space_id,
                        credential_id = %cred_id,
                        "deleting stale task credential"
                    );
                    let delete_url = format!("{PLATFORM_URL}/v1/task_credentials/{cred_id}?space_id={space_id}");
                    if let Err(e) = raw.delete(&delete_url).header("Authorization", format!("Bearer {token}")).send().await {
                        tracing::debug!(
                            target: "wxctl::substage::provider",
                            operation_id = %operation_id,
                            resource_type = "wml_deployment",
                            space_id = %space_id,
                            credential_id = %cred_id,
                            error = %e,
                            "failed to delete task credential"
                        );
                    }
                }
            }
        }
    }

    // Create task credentials using the current API key
    tracing::debug!(
        target: "wxctl::substage::provider",
        operation_id = %operation_id,
        resource_type = "wml_deployment",
        space_id = %space_id,
        "creating task credentials"
    );
    // Note: space_id is NOT supported on the create endpoint (account-level credentials)
    let create_url = format!("{PLATFORM_URL}/v1/task_credentials");
    let payload = json!({
        "name": "wxctl-generated-task-credentials",
        "description": "Auto-generated by wxctl for WML deployments",
        "type": "iam_api_key",
        "secret": {"api_key": client.get_auth_credential()}
    });

    let response = raw.post(&create_url).header("Authorization", format!("Bearer {token}")).header("Content-Type", "application/json").json(&payload).send().await.map_err(|e| anyhow!("[{operation_id}] Failed to create task credentials: {e}"))?;

    if response.status().is_success() {
        tracing::debug!(
            target: "wxctl::substage::provider",
            operation_id = %operation_id,
            resource_type = "wml_deployment",
            space_id = %space_id,
            "task credentials created; waiting for propagation"
        );
        tokio::time::sleep(std::time::Duration::from_secs(5)).await;
        Ok(())
    } else {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        // Non-fatal: warn but continue — task credentials may already exist or user can set them manually
        tracing::warn!(
            target: "wxctl::substage::provider",
            operation_id = %operation_id,
            resource_type = "wml_deployment",
            space_id = %space_id,
            http_status = %status,
            body = %body,
            "task credentials creation returned non-success (continuing)"
        );
        Ok(())
    }
}

/// Poll a deployment until its status reaches "ready" (or timeout).
/// Deployments with custom package extensions need extra startup time
/// while the runtime installs pip/conda packages.
async fn wait_for_deployment_ready(client: &HttpClient, deployment_id: &str, space_id: Option<&str>, operation_id: &str) -> Result<()> {
    let max_attempts = 60;

    crate::util::poll_until(max_attempts, std::time::Duration::from_secs(5), crate::util::PollTimeout::Bail(format!("[{operation_id}] Timed out waiting for deployment {deployment_id} to become ready")), None::<String>, |attempt, mut prev_state| async move {
        let mut path = format!("/ml/v4/deployments/{deployment_id}?version=2024-01-01");
        if let Some(sid) = space_id {
            path.push_str(&format!("&space_id={sid}"));
        }

        let spec = wxctl_core::client::RequestSpec::new(wxctl_core::client::Method::GET, &path).body(wxctl_core::client::BodyKind::None);
        let response: Value = client.execute(operation_id, spec).await?;

        let state = response.pointer("/entity/status/state").and_then(|v| v.as_str()).unwrap_or("unknown");

        if prev_state.as_deref() != Some(state) {
            tracing::debug!(
                target: "wxctl::substage::provider",
                operation_id = %operation_id,
                resource_type = "wml_deployment",
                deployment_id = %deployment_id,
                status = %state,
                attempt = attempt,
                max_attempts = max_attempts,
                "wml_deployment status observed"
            );
            prev_state = Some(state.to_string());
        }

        let outcome = match state {
            "ready" => crate::util::PollOutcome::Done(Value::Null),
            "failed" => {
                let message = response.pointer("/entity/status/failure/errors/0/message").and_then(|v| v.as_str()).unwrap_or("unknown error");
                crate::util::PollOutcome::Failed(format!("[{operation_id}] Deployment {deployment_id} failed: {message}"))
            }
            _ => crate::util::PollOutcome::Pending,
        };
        Ok((outcome, prev_state))
    })
    .await
    .map(|_| ())
}

impl ResourceHandler for WmlDeploymentHandler {
    fn pre_create<'a>(&'a self, resource: &'a mut Value, _fields: &'a [FieldDescriptor], client: &'a HttpClient, _endpoint: &'a str, operation_id: &'a str) -> Pin<Box<dyn Future<Output = Result<HookOutcome>> + Send + 'a>> {
        Box::pin(async move {
            // The ML API expects asset as {"id": "uuid"}, not a plain string
            if let Some(asset_id) = resource.get("asset").and_then(|v| v.as_str()).map(|s| s.to_string()) {
                resource["asset"] = json!({"id": asset_id});
                tracing::debug!(
                    target: "wxctl::substage::provider",
                    operation_id = %operation_id,
                    resource_type = "wml_deployment",
                    asset_id = %asset_id,
                    "wrapped asset as id object"
                );
            }

            // Online deployments reject hardware_spec at create time (it is PATCHable
            // later). Drop it on the online path so an `online: {}` create omits it.
            if resource.get("online").is_some() && resource.get("hardware_spec").is_some() {
                if let Some(obj) = resource.as_object_mut() {
                    obj.remove("hardware_spec");
                }
                tracing::debug!(
                    target: "wxctl::substage::provider",
                    operation_id = %operation_id,
                    resource_type = "wml_deployment",
                    "dropped hardware_spec on online deployment create"
                );
            }

            // Ensure task credentials exist for the space
            if let Some(space_id) = resource.get("space_id").and_then(|v| v.as_str()) {
                ensure_task_credentials(client, space_id, operation_id).await?;
            }

            Ok(HookOutcome::Continue)
        })
    }

    fn post_create<'a>(&'a self, resource: &'a Value, response: &'a mut Value, client: &'a HttpClient, operation_id: &'a str) -> Pin<Box<dyn Future<Output = Result<()>> + Send + 'a>> {
        Box::pin(async move {
            let deployment_id = crate::util::resource_id(response);

            let Some(deployment_id) = deployment_id else {
                tracing::debug!(
                    target: "wxctl::substage::provider",
                    operation_id = %operation_id,
                    resource_type = "wml_deployment",
                    reason = "missing_id_in_create_response",
                    "skipping readiness check"
                );
                return Ok(());
            };

            let space_id = resource.get("space_id").and_then(|v| v.as_str());
            wait_for_deployment_ready(client, deployment_id, space_id, operation_id).await
        })
    }
}
