use std::sync::Arc;
use wxctl_core::traits::ResourceHandler;

#[macro_use]
mod macros;
pub(crate) mod util;

mod cloud_object_storage;
mod common_core;
mod local; // was: utils
mod watsonx_ai;
mod watsonx_data; // was: data
mod watsonx_orchestrate; // was: orchestrate

/// Re-export of the compile-time dependency graph, now owned by `wxctl-schema`.
pub use wxctl_schema::dependency_graph;
pub use wxctl_schema::dependency_graph::PATH_FIELDS;

/// Schema-declared local path fields, generated by `build.rs`. Consumed by the
/// CLI's `resolve_file_paths` to resolve relative path fields against the config dir.
pub use wxctl_schema::load_all_schemas;

pub mod handlers {
    pub use super::cloud_object_storage::handlers as cloud_object_storage;
    pub use super::common_core::handlers as common_core;
    pub use super::local::handlers as local; // was: utils
    pub use super::watsonx_ai::handlers as watsonx_ai;
    pub use super::watsonx_data::handlers as watsonx_data; // was: data
    pub use super::watsonx_orchestrate::handlers as watsonx_orchestrate; // was: orchestrate
}

pub use watsonx_orchestrate::openapi::expand_openapi_resources;

/// Test-only helpers shared across the crate's unit-test modules.
#[cfg(test)]
pub(crate) mod test_support {
    use std::sync::{Mutex, MutexGuard};

    /// One process-wide lock guarding the global current directory. Any test that
    /// mutates `set_current_dir` (e.g. the python artifact tests) or reads it via a
    /// CWD-relative containment check (e.g. `validate_path` in the MCP artifact tests)
    /// must hold it, or those tests race on the shared process CWD across modules
    /// (cargo runs them on threads in one process). Poison is ignored.
    static CWD_LOCK: Mutex<()> = Mutex::new(());

    pub(crate) fn lock_cwd() -> MutexGuard<'static, ()> {
        CWD_LOCK.lock().unwrap_or_else(|p| p.into_inner())
    }
}

pub fn get_handler(resource_name: &str) -> Option<Arc<dyn ResourceHandler>> {
    common_core::get_handler(resource_name)
        .or_else(|| watsonx_data::get_handler(resource_name))
        .or_else(|| watsonx_orchestrate::get_handler(resource_name))
        .or_else(|| local::get_handler(resource_name))
        .or_else(|| watsonx_ai::get_handler(resource_name))
        .or_else(|| cloud_object_storage::get_handler(resource_name))
}

#[cfg(test)]
mod tests {
    use super::*;
    use wxctl_core::registry::ResourceDescriptor;

    #[test]
    fn test_all_schemas_parse_into_descriptors() {
        let schemas = load_all_schemas().expect("All schemas should parse via SchemaParser");

        assert!(!schemas.is_empty(), "Expected at least one schema to parse, got none");

        for schema in &schemas {
            let descriptor = ResourceDescriptor::from_schema(schema).unwrap_or_else(|e| panic!("Schema '{}' failed to produce ResourceDescriptor: {}", schema.resource.name, e));

            assert!(!descriptor.name.is_empty(), "Schema has empty name");
            assert!(!descriptor.service.is_empty(), "Schema '{}' has empty service", descriptor.name);
            assert!(!descriptor.kind.is_empty(), "Schema '{}' has empty kind", descriptor.name);
            assert!(!descriptor.id_field.is_empty(), "Schema '{}' has empty id_field", descriptor.name);
            assert!(!descriptor.endpoints.get.is_empty(), "Schema '{}' has empty get endpoint", descriptor.name);
            assert!(!descriptor.endpoints.create.is_empty(), "Schema '{}' has empty create endpoint", descriptor.name);
            assert!(!descriptor.endpoints.delete.is_empty(), "Schema '{}' has empty delete endpoint", descriptor.name);
        }

        let mut kinds: Vec<_> = schemas.iter().map(|s| s.resource.kind.clone()).collect();
        kinds.sort();
        let len = kinds.len();
        kinds.dedup();
        assert_eq!(kinds.len(), len, "Duplicate kind values found across schemas: {:?}", schemas.iter().map(|s| (s.resource.name.clone(), s.resource.kind.clone())).collect::<Vec<_>>());
    }
}
